name: saku_tani_mobile
description: "SakuTani adalah aplikasi manajemen keuangan digital yang dirancang khusus untuk membantu petani dalam mencatat pemasukan dan pengeluaran hasil pertanian secara praktis, real-time, dan mudah digunakan."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.8.0
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.6.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
